name: Push Event Workflow

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name : Install Packages 
      run : pip install pytest
      
    - name: Install sciPy dependencies
      run:  pip install pandas
      
    - name : Run unit tests 
      run : |
        pytest Source/AttoPhysics/TrajectoryPlotter/test_TrajData.py
        pytest Source/AttoPhysics/Global/test_BaseData.py