name: Push Event Workflow

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name : Install Packages 
      run : |
        pip install pytest
        pip install pandas
        pip install numpy
      
    - name : Run unit tests 
      run : |
        pytest Tests/test_TrajData.py
        pytest Tests/test_Base.py
        pytest Tests/test_ContourData.py